name: mobx_helper
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mobx: ^2.0.7+4

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0